/**
 * Languages available for the per-paragraph quick-translate widget.
 * Covers all major world languages that Google Translate supports.
 * `code` is the BCP-47 / Google `tl` value passed to the translate() helper.
 */
export interface TranslateLanguage {
  code: string;
  label: string;
  /** Native name shown alongside the English label */
  native: string;
}

export const TRANSLATE_LANGUAGES: ReadonlyArray<TranslateLanguage> = [
  { code: "af",    label: "Afrikaans",              native: "Afrikaans" },
  { code: "sq",    label: "Albanian",               native: "Shqip" },
  { code: "am",    label: "Amharic",                native: "አማርኛ" },
  { code: "ar",    label: "Arabic",                 native: "العربية" },
  { code: "hy",    label: "Armenian",               native: "Հայերեն" },
  { code: "az",    label: "Azerbaijani",            native: "Azərbaycan" },
  { code: "eu",    label: "Basque",                 native: "Euskara" },
  { code: "be",    label: "Belarusian",             native: "Беларуская" },
  { code: "bn",    label: "Bengali",                native: "বাংলা" },
  { code: "bs",    label: "Bosnian",                native: "Bosanski" },
  { code: "bg",    label: "Bulgarian",              native: "Български" },
  { code: "ca",    label: "Catalan",                native: "Català" },
  { code: "ceb",   label: "Cebuano",                native: "Cebuano" },
  { code: "ny",    label: "Chichewa",               native: "Chichewa" },
  { code: "zh-CN", label: "Chinese (Simplified)",   native: "中文(简体)" },
  { code: "zh-TW", label: "Chinese (Traditional)",  native: "中文(繁體)" },
  { code: "co",    label: "Corsican",               native: "Corsu" },
  { code: "hr",    label: "Croatian",               native: "Hrvatski" },
  { code: "cs",    label: "Czech",                  native: "Čeština" },
  { code: "da",    label: "Danish",                 native: "Dansk" },
  { code: "nl",    label: "Dutch",                  native: "Nederlands" },
  { code: "en",    label: "English",                native: "English" },
  { code: "eo",    label: "Esperanto",              native: "Esperanto" },
  { code: "et",    label: "Estonian",               native: "Eesti" },
  { code: "tl",    label: "Filipino",               native: "Filipino" },
  { code: "fi",    label: "Finnish",                native: "Suomi" },
  { code: "fr",    label: "French",                 native: "Français" },
  { code: "fy",    label: "Frisian",                native: "Frysk" },
  { code: "gl",    label: "Galician",               native: "Galego" },
  { code: "ka",    label: "Georgian",               native: "ქართული" },
  { code: "de",    label: "German",                 native: "Deutsch" },
  { code: "el",    label: "Greek",                  native: "Ελληνικά" },
  { code: "gu",    label: "Gujarati",               native: "ગુજરાતી" },
  { code: "ht",    label: "Haitian Creole",         native: "Kreyòl ayisyen" },
  { code: "ha",    label: "Hausa",                  native: "Hausa" },
  { code: "haw",   label: "Hawaiian",               native: "ʻŌlelo Hawaiʻi" },
  { code: "iw",    label: "Hebrew",                 native: "עברית" },
  { code: "hi",    label: "Hindi",                  native: "हिन्दी" },
  { code: "hmn",   label: "Hmong",                  native: "Hmoob" },
  { code: "hu",    label: "Hungarian",              native: "Magyar" },
  { code: "is",    label: "Icelandic",              native: "Íslenska" },
  { code: "ig",    label: "Igbo",                   native: "Igbo" },
  { code: "id",    label: "Indonesian",             native: "Bahasa Indonesia" },
  { code: "ga",    label: "Irish",                  native: "Gaeilge" },
  { code: "it",    label: "Italian",                native: "Italiano" },
  { code: "ja",    label: "Japanese",               native: "日本語" },
  { code: "jw",    label: "Javanese",               native: "Basa Jawa" },
  { code: "kn",    label: "Kannada",                native: "ಕನ್ನಡ" },
  { code: "kk",    label: "Kazakh",                 native: "Қазақ" },
  { code: "km",    label: "Khmer",                  native: "ខ្មែរ" },
  { code: "rw",    label: "Kinyarwanda",            native: "Kinyarwanda" },
  { code: "ko",    label: "Korean",                 native: "한국어" },
  { code: "ku",    label: "Kurdish",                native: "Kurdî" },
  { code: "ky",    label: "Kyrgyz",                 native: "Кыргызча" },
  { code: "lo",    label: "Lao",                    native: "ລາວ" },
  { code: "la",    label: "Latin",                  native: "Latina" },
  { code: "lv",    label: "Latvian",                native: "Latviešu" },
  { code: "lt",    label: "Lithuanian",             native: "Lietuvių" },
  { code: "lb",    label: "Luxembourgish",          native: "Lëtzebuergesch" },
  { code: "mk",    label: "Macedonian",             native: "Македонски" },
  { code: "mg",    label: "Malagasy",               native: "Malagasy" },
  { code: "ms",    label: "Malay",                  native: "Bahasa Melayu" },
  { code: "ml",    label: "Malayalam",              native: "മലയാളം" },
  { code: "mt",    label: "Maltese",                native: "Malti" },
  { code: "mi",    label: "Maori",                  native: "Māori" },
  { code: "mr",    label: "Marathi",                native: "मराठी" },
  { code: "mn",    label: "Mongolian",              native: "Монгол" },
  { code: "my",    label: "Myanmar (Burmese)",      native: "မြန်မာဘာသာ" },
  { code: "ne",    label: "Nepali",                 native: "नेपाली" },
  { code: "no",    label: "Norwegian",              native: "Norsk" },
  { code: "or",    label: "Odia (Oriya)",           native: "ଓଡ଼ିଆ" },
  { code: "ps",    label: "Pashto",                 native: "پښتو" },
  { code: "fa",    label: "Persian",                native: "فارسی" },
  { code: "pl",    label: "Polish",                 native: "Polski" },
  { code: "pt",    label: "Portuguese",             native: "Português" },
  { code: "pa",    label: "Punjabi",                native: "ਪੰਜਾਬੀ" },
  { code: "ro",    label: "Romanian",               native: "Română" },
  { code: "ru",    label: "Russian",                native: "Русский" },
  { code: "sm",    label: "Samoan",                 native: "Samoan" },
  { code: "gd",    label: "Scots Gaelic",           native: "Gàidhlig" },
  { code: "sr",    label: "Serbian",                native: "Српски" },
  { code: "st",    label: "Sesotho",                native: "Sesotho" },
  { code: "sn",    label: "Shona",                  native: "Shona" },
  { code: "sd",    label: "Sindhi",                 native: "سنڌي" },
  { code: "si",    label: "Sinhala",                native: "සිංහල" },
  { code: "sk",    label: "Slovak",                 native: "Slovenčina" },
  { code: "sl",    label: "Slovenian",              native: "Slovenščina" },
  { code: "so",    label: "Somali",                 native: "Soomaali" },
  { code: "es",    label: "Spanish",                native: "Español" },
  { code: "su",    label: "Sundanese",              native: "Basa Sunda" },
  { code: "sw",    label: "Swahili",                native: "Kiswahili" },
  { code: "sv",    label: "Swedish",                native: "Svenska" },
  { code: "tg",    label: "Tajik",                  native: "Тоҷикӣ" },
  { code: "ta",    label: "Tamil",                  native: "தமிழ்" },
  { code: "tt",    label: "Tatar",                  native: "Татар" },
  { code: "te",    label: "Telugu",                 native: "తెలుగు" },
  { code: "th",    label: "Thai",                   native: "ไทย" },
  { code: "tr",    label: "Turkish",                native: "Türkçe" },
  { code: "tk",    label: "Turkmen",                native: "Türkmen" },
  { code: "uk",    label: "Ukrainian",              native: "Українська" },
  { code: "ur",    label: "Urdu",                   native: "اردو" },
  { code: "ug",    label: "Uyghur",                 native: "ئۇيغۇرچە" },
  { code: "uz",    label: "Uzbek",                  native: "O'zbek" },
  { code: "vi",    label: "Vietnamese",             native: "Tiếng Việt" },
  { code: "cy",    label: "Welsh",                  native: "Cymraeg" },
  { code: "xh",    label: "Xhosa",                  native: "isiXhosa" },
  { code: "yi",    label: "Yiddish",                native: "ייִדיש" },
  { code: "yo",    label: "Yoruba",                 native: "Yorùbá" },
  { code: "zu",    label: "Zulu",                   native: "isiZulu" },
];
