// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/story-home/Enchanted.tsx": () => import("../components/mockups/story-home/Enchanted.tsx"),
  "./components/mockups/story-home/Space.tsx": () => import("../components/mockups/story-home/Space.tsx"),
  "./components/mockups/story-home/Storybook.tsx": () => import("../components/mockups/story-home/Storybook.tsx")
};
